domains/tipposh.com/tipposhFiles/routes/backend.php
<?php

use Illuminate\Support\Facades\Route;

Route::name('admin.')->group(function () {
    Route::get('login', 'BackendController@login')->name('login');
    Route::post('authentication', 'BackendController@authentication')->name('authentication');

    Route::get('forgetPass', 'AdminController@forgetPassForm')->name('forgetPassForm');
    Route::post('forgetPass', 'AdminController@forgetPass')->name('forgetPass');

    Route::get('changePass/{token}/{email}', 'AdminController@changePassForm')->name('changePassForm');
    Route::post('changePass', 'AdminController@changePass')->name('changePass');


    Route::middleware('adminAuth')->group(function () {
        Route::get('profile', 'BackendController@profile')->name('profile');
        Route::put('profileUpdate', 'BackendController@profileUpdate')->name('profileUpdate');
        Route::post('logout', 'AdminController@logout')->name('logout');
    });
});

Route::name('admin.')->middleware('adminAuth')->group(function () {
    Route::get('/', 'BackendController@dashboard')->name('dashboard');


    //******    admins Rule
    Route::get('rule/{id?}', 'Ad_AdminRuleController@destroy')->name('rule.delete');

    Route::resource('category', 'CategoryController');
    Route::resource('carousel', 'CarouselController');
    Route::resource('service', 'ServiceController');
    Route::resource('setting', 'SettingController');
    Route::resource('menu', 'MenuController');
    Route::resource('brand', 'BrandController');
    Route::resource('admins', 'AdminController');
    Route::resource('users', 'UserController');
    Route::resource('newsletter', 'AdminController');
    Route::resource('userRequestService', 'ServiceUserRequestController');

    Route::resource('order', 'OrderController');
	Route::resource('productDiscount', 'ProductDiscountController');

    Route::get('sale', 'PaymentController@saleAll')->name('sale.index');


    //*************************/ Blog
    Route::prefix('blog')->name('blog.')->group(function () {
        Route::get('addTag', 'BlogController@addTag')->name('addTag');
        Route::post('addTag', 'BlogController@addTag')->name('addTag');
        Route::get('removeTag', 'BlogController@removeTag')->name('removeTag');
        Route::post('removeTag', 'BlogController@removeTag')->name('removeTag');
        Route::post('images', 'BlogController@images')->name('images');
        Route::get('removImage', 'BlogController@removImage')->name('removImage');
    });
    Route::resource('blog', 'BlogController');
    //************/

    //*************************/ Product
    Route::prefix('product')->name('product.')->group(function () {
        Route::get('addTag', 'ProductController@addTag')->name('addTag');
        Route::get('removeTag', 'ProductController@removeTag')->name('removeTag');
        Route::get('removeColor', 'ProductController@removeColor')->name('removeColor');
        Route::get('removImage', 'ProductController@removImage')->name('removImage');
    });
    Route::resource('product', 'ProductController');
    //************/

    //*************************/ productComment
    Route::prefix('comment')->name('comment.')->group(function () {
        Route::get('/', 'ProductCommentController@index')->name('index');
        Route::get('replay', 'ProductCommentController@replay')->name('replay');
        Route::get('userHistory/{id}', 'ProductCommentController@userHistory')->name('userHistory');
        Route::get('changeStatus/{id}', 'ProductCommentController@changeStatus')->name('changeStatus');
        Route::get('destroy/{id}', 'ProductCommentController@delete')->name('delete');
    });
    //************/
});

domains/tipposh.com/tipposhFiles/routes/frontend.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index')->name('index');

Route::get('category/{slug}', 'FrontController@category')->name('category');
Route::post('category/{slug}', 'FrontController@category')->name('category');


Route::get('aboutUs', 'FrontController@aboutUs')->name('aboutUs');
Route::get('contactUs', 'FrontController@contactUs')->name('contactUs');
Route::get('help', 'FrontController@help')->name('help');
Route::get('order', 'FrontController@order')->name('order');

Route::get('userlogin', 'FrontController@userlogin')->name('user.login');
Route::get('userregisterForm', 'FrontController@userregisterForm')->name('user.registerForm');


Route::get('contact', 'FrontController@contact')->name('contact');
Route::get('userContactUs', 'FrontController@userContactUs');

Route::prefix('service')->name('service.')->group(function () {
    Route::get('/', 'ServiceController@services')->name('services');
    Route::get('/{slug}', 'ServiceController@details')->name('details');
});

Route::get('search', 'FrontController@search')->name('search'); // جستجو

Route::get('newsLetter', 'FrontController@newsLetter')->name('newsLetter');

Route::fallback(function () {
    return view('frontend.pages.404');
})->name('404');


Route::get('userServiceRequests', 'ServiceUserRequestController@add');


########### order
Route::prefix('order')->name('order.')->group(function () {
    Route::get('/{id}', 'OrderController@order')->name('new');
    Route::post('Save', 'OrderController@orderSave')->name('orderSave');
});

########### product
Route::prefix('product')->name('product.')->group(function () {
    Route::get('/{slug}', 'ProductController@show')->name('show');
    Route::get('all', 'ProductController@all')->name('all');
    Route::get('comment/Store', 'ProductController@commentStore')->name('commentStore');
});


########### Blog
Route::prefix('blog')->name('blog.')->group(function () {
    Route::get('/', 'BlogController@all')->name('all');
    Route::get('/{slug}', 'BlogController@details')->name('details');
    Route::get('commentStore', 'BlogController@commentStore')->name('commentStore');
    Route::get('category/{id}/{title}', 'BlogController@categoryPosts')->name('categoryPosts');
});


########### user
Route::prefix('user')->name('user.')->middleware('auth:web')->group(function () {
    Route::get('profile', 'UserController@profile')->name('profile');
    Route::post('profile', 'UserController@profileUpdate')->name('profileUpdate');
    Route::get('sale', 'UserController@sale')->name('sale');
    Route::get('basket', 'UserController@basket')->name('basket');
    Route::get('cash', 'UserController@cash')->name('cash');
    Route::get('likes', 'UserController@myLike')->name('likes');
    Route::get('requests', 'UserController@requests')->name('requests');
    Route::get('comments', 'UserController@comments')->name('comments');
    Route::get('removeComments', 'UserController@removeComments');
    Route::get('logout', 'UserController@logout')->name('logout');
    Route::get('password', 'UserController@password')->name('password');
    Route::post('password/update', 'UserController@passwordUpdate')->name('passwordUpdate');
});

Route::prefix('user')->name('user.')->middleware('guest')->group(function () {
    Route::post('loginTakePhone', 'UserController@loginTakePhone')->name('loginTakePhone');
    Route::post('login/VerifyCode', 'UserController@loginVerifyCode')->name('loginVerifyCode');
});


Route::prefix('user')->name('user.')->middleware('guest')->group(function () {
    Route::post('loginWithUsername', 'UserController@loginWithUsername')->name('loginWithUsername')->middleware('throttle:5,1');
});
Route::prefix('user')->name('user.')->group(function () {
    Route::get('like', 'LikeController@likeAndDislike');
});
### End user


########### basket
Route::prefix('basket')->name('basket.')->group(function () {
    Route::get('/', 'BasketController@index')->name('index');
    Route::get('all', 'BasketController@all');
    Route::get('add', 'BasketController@add');
    Route::post('add', 'BasketController@add')->name('addItem');
    Route::get('addOrRemove', 'BasketController@addOrRemove');
    Route::get('update', 'BasketController@update');
    Route::get('remove', 'BasketController@remove');
    Route::get('factor', 'BasketController@factor')->name('factor');
    Route::get('updateBasketAddress', 'BasketController@updateBasketAddress');
    Route::get('factorCompare', 'BasketController@factorCompare');
    Route::get('addDiscountCode', 'BasketController@addDiscountCode');
});
### End Product


Route::get('payment', 'PaymentController@payment')->name('payment');
Route::any('paymentCallback', 'PaymentController@paymentCallback')->name('paymentCallback');



########### Sitemap
Route::get('sitemap.xml','SitemapController@sitemap');
Route::get('sitemap-static.xml','SitemapController@statics');
Route::get('sitemap-category.xml','SitemapController@category');
Route::get('sitemap-post.xml','SitemapController@post');
Route::get('sitemap-product.xml','SitemapController@product');
### End Sitemap

domains/tipposh.com/tipposhFiles/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

domains/tipposh.com/tipposhFiles/app/Models/Brand.php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Category
 * @package App
 */
class Brand extends Model
{
    protected $table = 'brand';
    public $timestamps = false;
    protected $fillable = ['caption', 'photo'];
}

domains/tipposh.com/tipposhFiles/app/Http/Controllers/BrandController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Image;
use Auth;

use App\Models\Brand;

class BrandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $all = Brand::orderBy('id', 'desc')->paginate(10);
        return view('backend.pages.brand.all', compact('all'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.pages.brand.new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            [
                'caption'            => 'required',
                'photo'              => 'required',
            ]
        );

        if ($request->hasFile('photo')) {
            $rond = random_int(10000000000, 99999999999);
            $fileType = $request->photo->extension();
            $photoUrl = "assets/images/$rond.$fileType";
            $image = Image::make($request->file('photo'));
            $image->resize(150 , 100)->save($photoUrl , 100);
        }

        if(!isset($photoUrl))
            $photoUrl = "";

            Brand::create([
            'photo' => $photoUrl,
            'caption' =>  $request->caption,
        ]);

        return redirect()->back()->with('prossesOk', 'عملیات  با موفقیت انجام شد');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    { }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $brand = Brand::find($id);
        return view('backend.pages.brand.edit', compact('brand'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate(
            [
                'caption'            => 'required',
            ]
        );

        if ($request->hasFile('photo')) {
            $rond = random_int(10000000000, 99999999999);
            $fileType = $request->photo->extension();
            $photoUrl = "assets/images/$rond.$fileType";
            $image = Image::make($request->file('photo'));
            $image->resize(150 , 100)->save($photoUrl , 100);

            Brand::find($id)->update(['photo' => $photoUrl,]);

        }

        Brand::find($id)->update(['caption' =>  $request->caption,]);

        return redirect()->back()->with('prossesOk', 'عملیات  با موفقیت انجام شد');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (file_exists(Brand::find($id)->photo))
            unlink(Brand::find($id)->photo);
        Brand::destroy($id);
        return redirect()->back()->with('prossesOk', 'عملیات  با موفقیت انجام شد ');
    }
}

domains/tipposh.com/tipposhFiles/resources/views/backend/pages/brand/all.blade.php
@extends('backend.layout.app')

@section('title') همه برند ها  @stop

@section('pageInfo')
    <h3 class="page-title">برند</h3>
    <!-- begin::breadcrumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a>برنامه ها</a></li>
            <li class="breadcrumb-item"><a href="{{route('admin.brand.index')}}"> برند</a></li>
            <li class="breadcrumb-item active" aria-current="page">همه</li>
        </ol>
    </nav>
    <!-- end::breadcrumb -->
@stop

@section('css')  @stop
@section('js')  @stop

@section('content')
    <main class="main-content">
        <div class="row">

            <div class="col-md-12">
                @include('backend.layout.errors')
            </div>

            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <h6 class="card-title">لیست برند ها </h6>

                        <a href="{{route('admin.brand.create')}}" title="اضافه کردن رکود جدید" class="float-right">
                            <button type="button" class="btn btn-whatsapp btn-floating btn-lg btn-pulse">
                                <i class="ti-plus"></i>
                            </button>
                        </a>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">عنوان</th>
                                    <th scope="col">عکس</th>
                                    <th class="text-right" scope="col">عمل</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($all as $key => $item)
                                    <tr>
                                        <th scope="row">{{$key + 1}}</th>
                                        <td>{{$item->caption}}</td>
                                        <td><img src="{{asset($item->photo)}}" alt=""></td>

                                        
                                        <td class="text-right">
                                            <div class="dropdown">
                                                <a href="#" class="btn btn-light btn-floating btn-icon btn-sm"
                                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a href="{{route('admin.brand.edit', $item->id)}}">
                                                        <button class="dropdown-item" type="button">
                                                            مشاهده و بروزرسانی
                                                        </button>
                                                    </a>

                                                    <button class="dropdown-item" type="button"
                                                            onclick="deleteRecordFromTable({{$item->id}})">حذف کردن
                                                    </button>

                                                    <form id="deleteRecordFrom_{{$item->id}}"
                                                          action="{{route('admin.brand.destroy', $item->id)}}"
                                                          method="post" style="display: none;">
                                                        @csrf
                                                        @method('delete')
                                                    </form>

                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
@stop

domains/tipposh.com/tipposhFiles/resources/views/backend/pages/brand/edit.blade.php
@extends('backend.layout.app')

@section('title') نمایش برند   @stop
@section('pageInfo')
	<h3 class="page-title">برند</h3>
	<!-- begin::breadcrumb -->
	<nav aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a>برنامه ها</a></li>
			<li class="breadcrumb-item"><a href="{{route('admin.brand.index')}}"> برند</a></li>
			<li class="breadcrumb-item active" aria-current="page">نمایش</li>
		</ol>
	</nav>
	<!-- end::breadcrumb -->
@stop
@section('css')  @stop
@section('js')  @stop

@section('content')
	<main class="main-content">
		<div class="row">

			<div class="col-md-12">
				@include('backend.layout.errors')
			</div>

			<div class="col-md-12">
				<div class="card">
					<div class="card-body">
						<h6 class="card-title">نمایش برند </h6>
						<form method="post" action="{{route('admin.brand.update' , $brand->id )}}" enctype="multipart/form-data">
							@method('put')
							@csrf


							<div class="form-row">
								<div class="col-md-4 mb-3">
									<label for="caption">عنوان</label>
									<input type="text" class="form-control" id="caption" name="caption"
										   placeholder="عنوان" value="{{$brand->caption}}" required>
								</div>

								<div class="col-md-4 mb-3">
									<label for="validationServer04">انتخاب عکس</label>
									<div class="custom-file">
										<input type="file" class="custom-file-input" id="customFile" name="photo">
										<label class="custom-file-label" for="customFile">انتخاب فایل</label>
									</div>
								</div>

							</div>

							<button class="btn btn-primary" type="submit">ثبت </button>
						</form>
					</div>
				</div>

			</div>
		</div>

	</main>
@stop

domains/tipposh.com/tipposhFiles/resources/views/backend/pages/brand/new.blade.php
@extends('backend.layout.app')

@section('title') برند جدید  @stop
@section('pageInfo')
    <h3 class="page-title">برند</h3>
    <!-- begin::breadcrumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a>برنامه ها</a></li>
            <li class="breadcrumb-item"><a href="{{route('admin.brand.index')}}"> برند</a></li>
            <li class="breadcrumb-item active" aria-current="page">جدید</li>
        </ol>
    </nav>
    <!-- end::breadcrumb -->
@stop
@section('css')  @stop
@section('js')  @stop

@section('content')
    <main class="main-content">
        <div class="row">

            <div class="col-md-12">
                @include('backend.layout.errors')
            </div>

            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <h6 class="card-title">اضافه کردن برند جدید</h6>
                        <form method="post" action="{{route('admin.brand.store')}}" enctype="multipart/form-data">
                            @csrf

                            <div class="form-row">
                                <div class="col-md-4 mb-3">
                                    <label for="caption">عنوان</label>
                                    <input type="text" class="form-control" id="caption" name="caption"
                                           placeholder="عنوان" value="{{old('caption')}}" required>
                                </div>

                                <div class="col-md-4 mb-3">
                                    <label for="validationServer04">انتخاب عکس</label>
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="customFile" name="photo">
                                        <label class="custom-file-label" for="customFile">انتخاب فایل</label>
                                    </div>
                                </div>

                            </div>

                            <button class="btn btn-primary" type="submit">ثبت</button>
                        </form>
                    </div>
                </div>

            </div>
        </div>

    </main>
@stop