domains/tipposh.com/tipposhFiles/routes/backend.php
<?php

use Illuminate\Support\Facades\Route;

Route::name('admin.')->group(function () {
    Route::get('login', 'BackendController@login')->name('login');
    Route::post('authentication', 'BackendController@authentication')->name('authentication');

    Route::get('forgetPass', 'AdminController@forgetPassForm')->name('forgetPassForm');
    Route::post('forgetPass', 'AdminController@forgetPass')->name('forgetPass');

    Route::get('changePass/{token}/{email}', 'AdminController@changePassForm')->name('changePassForm');
    Route::post('changePass', 'AdminController@changePass')->name('changePass');


    Route::middleware('adminAuth')->group(function () {
        Route::get('profile', 'BackendController@profile')->name('profile');
        Route::put('profileUpdate', 'BackendController@profileUpdate')->name('profileUpdate');
        Route::post('logout', 'AdminController@logout')->name('logout');
    });
});

Route::name('admin.')->middleware('adminAuth')->group(function () {
    Route::get('/', 'BackendController@dashboard')->name('dashboard');


    //******    admins Rule
    Route::get('rule/{id?}', 'Ad_AdminRuleController@destroy')->name('rule.delete');

    Route::resource('category', 'CategoryController');
    Route::resource('carousel', 'CarouselController');
    Route::resource('service', 'ServiceController');
    Route::resource('setting', 'SettingController');
    Route::resource('menu', 'MenuController');
    Route::resource('brand', 'BrandController');
    Route::resource('admins', 'AdminController');
    Route::resource('users', 'UserController');
    Route::resource('newsletter', 'AdminController');
    Route::resource('userRequestService', 'ServiceUserRequestController');

    Route::resource('order', 'OrderController');
	Route::resource('productDiscount', 'ProductDiscountController');

    Route::get('sale', 'PaymentController@saleAll')->name('sale.index');


    //*************************/ Blog
    Route::prefix('blog')->name('blog.')->group(function () {
        Route::get('addTag', 'BlogController@addTag')->name('addTag');
        Route::post('addTag', 'BlogController@addTag')->name('addTag');
        Route::get('removeTag', 'BlogController@removeTag')->name('removeTag');
        Route::post('removeTag', 'BlogController@removeTag')->name('removeTag');
        Route::post('images', 'BlogController@images')->name('images');
        Route::get('removImage', 'BlogController@removImage')->name('removImage');
    });
    Route::resource('blog', 'BlogController');
    //************/

    //*************************/ Product
    Route::prefix('product')->name('product.')->group(function () {
        Route::get('addTag', 'ProductController@addTag')->name('addTag');
        Route::get('removeTag', 'ProductController@removeTag')->name('removeTag');
        Route::get('removeColor', 'ProductController@removeColor')->name('removeColor');
        Route::get('removImage', 'ProductController@removImage')->name('removImage');
    });
    Route::resource('product', 'ProductController');
    //************/

    //*************************/ productComment
    Route::prefix('comment')->name('comment.')->group(function () {
        Route::get('/', 'ProductCommentController@index')->name('index');
        Route::get('replay', 'ProductCommentController@replay')->name('replay');
        Route::get('userHistory/{id}', 'ProductCommentController@userHistory')->name('userHistory');
        Route::get('changeStatus/{id}', 'ProductCommentController@changeStatus')->name('changeStatus');
        Route::get('destroy/{id}', 'ProductCommentController@delete')->name('delete');
    });
    //************/
});

domains/tipposh.com/tipposhFiles/routes/frontend.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index')->name('index');

Route::get('category/{slug}', 'FrontController@category')->name('category');
Route::post('category/{slug}', 'FrontController@category')->name('category');


Route::get('aboutUs', 'FrontController@aboutUs')->name('aboutUs');
Route::get('contactUs', 'FrontController@contactUs')->name('contactUs');
Route::get('help', 'FrontController@help')->name('help');
Route::get('order', 'FrontController@order')->name('order');

Route::get('userlogin', 'FrontController@userlogin')->name('user.login');
Route::get('userregisterForm', 'FrontController@userregisterForm')->name('user.registerForm');


Route::get('contact', 'FrontController@contact')->name('contact');
Route::get('userContactUs', 'FrontController@userContactUs');

Route::prefix('service')->name('service.')->group(function () {
    Route::get('/', 'ServiceController@services')->name('services');
    Route::get('/{slug}', 'ServiceController@details')->name('details');
});

Route::get('search', 'FrontController@search')->name('search'); // جستجو

Route::get('newsLetter', 'FrontController@newsLetter')->name('newsLetter');

Route::fallback(function () {
    return view('frontend.pages.404');
})->name('404');


Route::get('userServiceRequests', 'ServiceUserRequestController@add');


########### order
Route::prefix('order')->name('order.')->group(function () {
    Route::get('/{id}', 'OrderController@order')->name('new');
    Route::post('Save', 'OrderController@orderSave')->name('orderSave');
});

########### product
Route::prefix('product')->name('product.')->group(function () {
    Route::get('/{slug}', 'ProductController@show')->name('show');
    Route::get('all', 'ProductController@all')->name('all');
    Route::get('comment/Store', 'ProductController@commentStore')->name('commentStore');
});


########### Blog
Route::prefix('blog')->name('blog.')->group(function () {
    Route::get('/', 'BlogController@all')->name('all');
    Route::get('/{slug}', 'BlogController@details')->name('details');
    Route::get('commentStore', 'BlogController@commentStore')->name('commentStore');
    Route::get('category/{id}/{title}', 'BlogController@categoryPosts')->name('categoryPosts');
});


########### user
Route::prefix('user')->name('user.')->middleware('auth:web')->group(function () {
    Route::get('profile', 'UserController@profile')->name('profile');
    Route::post('profile', 'UserController@profileUpdate')->name('profileUpdate');
    Route::get('sale', 'UserController@sale')->name('sale');
    Route::get('basket', 'UserController@basket')->name('basket');
    Route::get('cash', 'UserController@cash')->name('cash');
    Route::get('likes', 'UserController@myLike')->name('likes');
    Route::get('requests', 'UserController@requests')->name('requests');
    Route::get('comments', 'UserController@comments')->name('comments');
    Route::get('removeComments', 'UserController@removeComments');
    Route::get('logout', 'UserController@logout')->name('logout');
    Route::get('password', 'UserController@password')->name('password');
    Route::post('password/update', 'UserController@passwordUpdate')->name('passwordUpdate');
});

Route::prefix('user')->name('user.')->middleware('guest')->group(function () {
    Route::post('loginTakePhone', 'UserController@loginTakePhone')->name('loginTakePhone');
    Route::post('login/VerifyCode', 'UserController@loginVerifyCode')->name('loginVerifyCode');
});


Route::prefix('user')->name('user.')->middleware('guest')->group(function () {
    Route::post('loginWithUsername', 'UserController@loginWithUsername')->name('loginWithUsername')->middleware('throttle:5,1');
});
Route::prefix('user')->name('user.')->group(function () {
    Route::get('like', 'LikeController@likeAndDislike');
});
### End user


########### basket
Route::prefix('basket')->name('basket.')->group(function () {
    Route::get('/', 'BasketController@index')->name('index');
    Route::get('all', 'BasketController@all');
    Route::get('add', 'BasketController@add');
    Route::post('add', 'BasketController@add')->name('addItem');
    Route::get('addOrRemove', 'BasketController@addOrRemove');
    Route::get('update', 'BasketController@update');
    Route::get('remove', 'BasketController@remove');
    Route::get('factor', 'BasketController@factor')->name('factor');
    Route::get('updateBasketAddress', 'BasketController@updateBasketAddress');
    Route::get('factorCompare', 'BasketController@factorCompare');
    Route::get('addDiscountCode', 'BasketController@addDiscountCode');
});
### End Product


Route::get('payment', 'PaymentController@payment')->name('payment');
Route::any('paymentCallback', 'PaymentController@paymentCallback')->name('paymentCallback');



########### Sitemap
Route::get('sitemap.xml','SitemapController@sitemap');
Route::get('sitemap-static.xml','SitemapController@statics');
Route::get('sitemap-category.xml','SitemapController@category');
Route::get('sitemap-post.xml','SitemapController@post');
Route::get('sitemap-product.xml','SitemapController@product');
### End Sitemap

domains/tipposh.com/tipposhFiles/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

domains/tipposh.com/tipposhFiles/app/Http/Controllers/BackendController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\Admin;
use Hash;
use Image;

class BackendController extends Controller
{

    public function dashboard()
    {
        return view('backend.pages.dashboard');
    }


    //*************************************     authentication Section
    public function login()
    {
        if (Auth()->guard('admin')->check())
            return redirect()->route('admin.dashboard');

        return view('backend.auth.login');
    }

    public function authentication(Request $request)
    {
        if (Auth::guard('admin')->attempt(['email' => Request()->email, 'password' => Request()->password])) {
            return redirect()->route('admin.dashboard');
        }
        return redirect()->back()->withInput();
    }

    /**
     * Log the user out of the application.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function logout(Request $request)
    {
        Auth::logout();
    }

    //******************************************************


    public function profile()
    {
        $admin = Auth::guard('admin')->user();
        return view('backend.pages.admin.profile', compact('admin'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function profileUpdate(Request $request)
    {
        $request->validate(
            [
                'name' => ['required', 'string', 'max:255'],
                'phone' => ['min:11', 'max:11'],
            ]);

        $admin = Auth::guard('admin')->user();
        $admin->name = Request()->name;
        $admin->phone = Request()->phone;
        $admin->address = Request()->address;

        if (isset($request->password))
            $admin->password = Hash::make(Request()->password);

        $admin->save();

        if ($request->hasFile('file')) {
            $fileType = $request->file->extension();
            $rond = random_int(10000000000, 99999999999);
            $url = "assets/images/user/admins/$rond.$fileType";
            $image = Image::make($request->file('file'));
            $image->resize(100, 100)->save($url, 100);
            Admin::find($admin->id)->update(['imageProfile' => $url]);
        }

        return redirect()->back()->with('prossesOk', 'اطلاعات شما با موفقیت بروزرسانی شد');
    }
}

domains/tipposh.com/tipposhFiles/resources/views/backend/layout/1-loader.blade.php
<!-- begin::page loader-->
<div class="page-loader">
    <div class="spinner-border"></div>
</div>
<!-- end::page loader -->

domains/tipposh.com/tipposhFiles/resources/views/backend/layout/2-userProfile.blade.php
<!-- begin::sidebar user profile -->
<div class="sidebar" id="userProfile">
    <div class="text-center p-4">
        <figure class="avatar avatar-state-success avatar-lg mb-4">
            <img src='{{asset("assets/backend/media/image/avatar.jpg")}}' class="rounded-circle" alt="image">
        </figure>
        <h4 class="text-primary m-b-10">جان اسنو</h4>
        <p class="text-muted d-flex align-items-center justify-content-center line-height-0 mb-0">
            رهبر تیم <a href="#" class="ml-2" data-toggle="tooltip" title="تنظیمات" data-sidebar-open="#settings"> <i class="ti-settings"></i> </a>
        </p>
    </div>
    <hr class="m-0">
    <div class="p-4">
        <div class="mb-4">
            <h6 class="font-size-13 mb-3">
                تکمیل پروفایل
                <span class="float-right primary-font">%25</span>
            </h6>
            <div class="progress m-b-20" style="height: 5px;">
                <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
        </div>
        <div class="mb-4">
            <h6 class="font-size-13 mb-3">
                ذخیره سازی
                <span class="float-right primary-font">%77</span>
            </h6>
            <div class="progress m-b-20" style="height: 5px;">
                <div class="progress-bar bg-danger" role="progressbar" style="width: 77%;" aria-valuenow="77" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
        </div>
        <div class="mb-4">
            <h6 class="font-size-13 mb-3 ">
                وظایف انجام شده
                <span class="float-right primary-font">%40</span>
            </h6>
            <div class="progress m-b-20" style="height: 5px;">
                <div class="progress-bar bg-success" role="progressbar" style="width: 40%;" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
        </div>
        <div class="mb-4">
            <h6 class="font-size-13 mb-3 pt-2">درباره</h6>
            <p class="text-muted">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک</p>
        </div>
        <div class="mb-4">
            <h6 class="font-size-13 mb-3">شهر</h6>
            <p class="text-muted">تبریز / ایران</p>
        </div>
        <div class="mb-4">
            <h6 class="font-size-13 mb-3">شبکه های اجتماعی</h6>
            <ul class="list-inline mb-4">
                <li class="list-inline-item">
                    <a href="#" class="btn btn-sm btn-floating btn-facebook">
                        <i class="fa fa-facebook"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="#" class="btn btn-sm btn-floating btn-twitter">
                        <i class="fa fa-twitter"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="#" class="btn btn-sm btn-floating btn-dribbble">
                        <i class="fa fa-dribbble"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="#" class="btn btn-sm btn-floating btn-whatsapp">
                        <i class="fa fa-whatsapp"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="#" class="btn btn-sm btn-floating btn-linkedin">
                        <i class="fa fa-linkedin"></i>
                    </a>
                </li>
            </ul>
        </div>
        <div class="mb-4">
            <h6 class="font-size-13 mb-3">تنظیمات</h6>
            <div class="form-group">
                <div class="form-item custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" id="customSwitch11">
                    <label class="custom-control-label" for="customSwitch11">مسدود کردن</label>
                </div>
            </div>
            <div class="form-group">
                <div class="form-item custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" checked id="customSwitch12">
                    <label class="custom-control-label" for="customSwitch12">بیصدا کردن</label>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end::sidebar user profile -->

domains/tipposh.com/tipposhFiles/resources/views/backend/layout/3-settings.blade.php
<!-- begin::sidebar settings -->
<div class="sidebar" id="settings">
    <header>
        <i class="ti-settings"></i> تنظیمات
    </header>
    <div class="p-4">
        <div class="mb-3">
            <h6 class="font-size-13 mb-3 text-muted">سیستم</h6>
            <ul class="list-group list-group-flush">
                <li class="list-group-item d-flex justify-content-between p-l-r-0 p-t-b-5">
                    <span>به روز رسانی خودکار</span>
                    <div class="custom-control custom-switch">
                        <input type="checkbox" class="custom-control-input" id="customSwitch1" checked>
                        <label class="custom-control-label" for="customSwitch1"></label>
                    </div>
                </li>
                <li class="list-group-item d-flex justify-content-between p-l-r-0 p-t-b-5">
                    <span>وضعیت کنونی</span>
                    <div class="custom-control custom-switch">
                        <input type="checkbox" class="custom-control-input" id="customSwitch2" checked>
                        <label class="custom-control-label" for="customSwitch2"></label>
                    </div>
                </li>
                <li class="list-group-item d-flex justify-content-between p-l-r-0 p-t-b-5">
                    <span>پیشنهادات کاربران</span>
                    <div class="custom-control custom-switch">
                        <input type="checkbox" class="custom-control-input" id="customSwitch3" checked>
                        <label class="custom-control-label" for="customSwitch3"></label>
                    </div>
                </li>
            </ul>
        </div>
        <div class="mb-3">
            <h6 class="font-size-13 mb-3 text-muted">حساب کاربری</h6>
            <ul class="list-group list-group-flush">
                <li class="list-group-item d-flex justify-content-between p-l-r-0 p-t-b-5">
                    <span>امنیت حساب کاربری ارشد</span>
                    <div class="custom-control custom-switch">
                        <input type="checkbox" class="custom-control-input" id="customSwitch4">
                        <label class="custom-control-label" for="customSwitch4"></label>
                    </div>
                </li>
                <li class="list-group-item d-flex justify-content-between p-l-r-0 p-t-b-5">
                    <span>حفاظت حساب کاربری</span>
                    <div class="custom-control custom-switch">
                        <input type="checkbox" class="custom-control-input" id="customSwitch5" checked>
                        <label class="custom-control-label" for="customSwitch5"></label>
                    </div>
                </li>
            </ul>
        </div>
        <div class="mb-3">
            <h6 class="font-size-13 mb-3 text-muted">اعلان ها</h6>
            <ul class="list-group list-group-flush">
                <li class="list-group-item d-flex justify-content-between p-l-r-0 p-t-b-5">
                    <span>اعلان های مرورگر</span>
                    <div class="custom-control custom-switch">
                        <input type="checkbox" class="custom-control-input" id="customSwitch6">
                        <label class="custom-control-label" for="customSwitch6"></label>
                    </div>
                </li>
                <li class="list-group-item d-flex justify-content-between p-l-r-0 p-t-b-5">
                    <span>اعلان های موبایل</span>
                    <div class="custom-control custom-switch">
                        <input type="checkbox" class="custom-control-input" id="customSwitch7">
                        <label class="custom-control-label" for="customSwitch7"></label>
                    </div>
                </li>
                <li class="list-group-item d-flex justify-content-between p-l-r-0 p-t-b-5">
                    <span>اشتراک ایمیل</span>
                    <div class="custom-control custom-switch">
                        <input type="checkbox" class="custom-control-input" id="customSwitch8">
                        <label class="custom-control-label" for="customSwitch8"></label>
                    </div>
                </li>
                <li class="list-group-item d-flex justify-content-between p-l-r-0 p-t-b-5">
                    <span>اعلان های sms</span>
                    <div class="custom-control custom-switch">
                        <input type="checkbox" class="custom-control-input" id="customSwitch9" checked>
                        <label class="custom-control-label" for="customSwitch9"></label>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- end::sidebar settings -->

domains/tipposh.com/tipposhFiles/resources/views/backend/layout/4-navigation.blade.php
<!-- begin::navigation -->
<div class="navigation">
    <div class="navigation-icon-menu">
        <ul>
            <li data-toggle="tooltip" title="آمار سایت">
                <a href="#navigationDashboards" title="آمار سایت">
                    <i class="icon ti-pie-chart"></i>
                    <span class="badge badge-warning">2</span>
                </a>
            </li>
            <li data-toggle="tooltip" title="برنامه ها" id="mangeNavigationApps">
                <a href="#navigationApps" title="برنامه ها">
                    <i class="icon ti-package"></i>
                </a>
            </li>
        </ul>
        <ul>
            <li data-toggle="tooltip" title="ویرایش پروفایل">
                <a href="{{route('admin.profile')}}" class="go-to-page">
                    <i class="icon ti-settings"></i>
                </a>
            </li>
            <li data-toggle="tooltip" title="خروج">
                <a href="{{route('admin.logout')}}" class="go-to-page">
                    <i class="icon ti-power-off"></i>
                </a>
            </li>
        </ul>
    </div>
    <div class="navigation-menu-body">
        <ul id="navigationDashboards">
            <li>
                <a href="#" class="mb-2">
                    <div class="d-flex align-items-center">
                        <div>
                            <div class="icon-block bg-warning text-white mr-3">
                                <i class="ti-bar-chart"></i>
                            </div>
                        </div>
                        <div>
                            <h6 class="font-size-13 line-height-22 primary-font m-b-5">مجموع فروش</h6>
                            <h4 class="m-b-0 primary-font font-weight-bold line-height-30">
                                {{\App\Models\Sale::all()->sum('count')}}
                            </h4>
                        </div>
                    </div>
                </a>
            </li>

            <li>
                <a href="#">
                    <div class="d-flex align-items-center">
                        <div>
                            <div class="icon-block bg-info text-white mr-3">
                                <i class="ti-user"></i>
                            </div>
                        </div>
                        <div>
                            <h6 class="font-size-13 line-height-22 primary-font m-b-5">مجموع کاربران</h6>
                            <h4 class="m-b-0 primary-font font-weight-bold line-height-30">
                                {{\App\Models\User::all()->count()}}
                            </h4>
                        </div>
                    </div>
                </a>
            </li>

        </ul>

        <ul id="navigationApps">
            <li class="navigation-divider">برنامه ها</li>

            <li><a href="{{route('admin.dashboard')}}">داشبرد</a> </li>
            <li><a href="{{route('admin.admins.index')}}"> اعضا </a> </li>
            <li><a href="{{route('admin.users.index')}}"> کاربران </a> </li>
            <li><a href="{{route('admin.product.index')}}"> محصولات </a> </li>
            <li><a href="{{route('admin.sale.index')}}"> فروش </a> </li>
            <li><a href="{{route('admin.productDiscount.index')}}">تخفیف </a> </li>
            <li><a href="{{route('admin.comment.index')}}"> نظرات  </a> </li>
            <li><a href="{{route('admin.category.index')}}"> دسته بندی </a> </li>
            <li><a href="{{route('admin.setting.index')}}">تنظیمات </a> </li>
            <li><a href="{{route('admin.carousel.index')}}"> اسلایدر </a> </li>
            <li><a href="{{route('admin.blog.index')}}"> وبلاگ  </a> </li>
            <li><a href="{{route('admin.brand.index')}}"> برند  </a> </li>


        </ul>
    </div>
</div>
<!-- end::navigation -->

@section('navJS')
    <script>
        $(document).ready(function () {

            var headerLocation = window.location.href;

            var spl = headerLocation.split("/");

            $('.navigation-menu-body a').each(function () {
                if ( ($(this).attr('href').includes(spl[4])) || $(this).attr('href') == headerLocation  || ($(this).attr('href') + '/') == headerLocation) {
                    $(this).addClass('active');
                    $(this).parents('ul').addClass('navigation-active');

                    var parentId = "#" + $(this).parents('ul').attr('id');

                    $("[href='"+parentId+"']").parent().addClass('active');
                }
            });
        });
    </script>
@stop

domains/tipposh.com/tipposhFiles/resources/views/backend/layout/5-header.blade.php
<!-- begin::header -->
<div class="header">

    <!-- begin::header logo -->
    <div class="header-logo">
        <a href="{{route('admin.dashboard')}}">
            @php $logo = \App\Models\Setting::where('key' ,"logo" )->first(); @endphp
            <img src="{{asset($logo->value)}}" class="large-logo" style="width: 70px ; height: 50px">
        </a>
    </div>
    <!-- end::header logo -->

    <!-- begin::header body -->
    <div class="header-body">

        <div class="header-body-left">

            @yield('pageInfo')

        </div>


    </div>
    <!-- end::header body -->

</div>
<!-- end::header -->

domains/tipposh.com/tipposhFiles/resources/views/backend/layout/app.blade.php
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title')</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href='{{asset("assets/backend/media/image/favicon.png")}}'>

    <!-- Theme Color -->
    <meta name="theme-color" content="#5867dd">

    <!-- Plugin styles -->
    <link rel="stylesheet" href='{{asset("assets/backend/vendors/bundle.css")}}' type="text/css">

    <!-- Datepicker -->
    <link rel="stylesheet" href='{{asset("assets/backend/vendors/datepicker/daterangepicker.css")}}'>

    <!-- Slick -->
    <link rel="stylesheet" href='{{asset("assets/backend/vendors/slick/slick.css")}}'>
    <link rel="stylesheet" href='{{asset("assets/backend/vendors/slick/slick-theme.css")}}'>

    <!-- Vmap -->
    <link rel="stylesheet" href='{{asset("assets/backend/vendors/vmap/jqvmap.min.css")}}'>

    <link rel="stylesheet" type="text/css" href="{{asset('assets/frontend/fonts/fontawesome5/fontawesome5.css')}}" />
    <link rel="stylesheet" type="text/css" href="{{asset('assets/frontend/fonts/fontawesome4/fontawesome4.css')}}" />
    <link rel="stylesheet" type="text/css" href="{{asset('assets/frontend/fonts/iransans/font.css')}}" />

    <!-- App styles -->
    <link rel="stylesheet" href='{{asset("assets/backend/css/app.css")}}' type="text/css">

    @yield('css')

    <link rel="stylesheet" href='{{asset("assets/backend/css/demo.css")}}' type="text/css">


</head>

<body>

@include('backend.layout.1-loader')
@include('backend.layout.2-userProfile')
@include('backend.layout.3-settings')
@include('backend.layout.4-navigation')
@include('backend.layout.5-header')

@yield('content')



<!-- Plugin scripts -->
<script src='{{asset("assets/backend/vendors/bundle.js")}}'></script>

<!-- Chartjs -->
<script src='{{asset("assets/backend/vendors/charts/chartjs/chart.min.js")}}'></script>

<!-- Circle progress -->
<script src='{{asset("assets/backend/vendors/circle-progress/circle-progress.min.js")}}'></script>

<!-- Peity -->
<script src='{{asset("assets/backend/vendors/charts/peity/jquery.peity.min.js")}}'></script>
<script src='{{asset("assets/backend/assets/js/examples/charts/peity.js")}}'></script>

<!-- Datepicker -->
<script src='{{asset("assets/backend/vendors/datepicker/daterangepicker.js")}}'></script>

<!-- Slick -->
<script src='{{asset("assets/backend/vendors/slick/slick.min.js")}}'></script>

<!-- Vamp -->
<script src='{{asset("assets/backend/vendors/vmap/jquery.vmap.min.js")}}'></script>
<script src='{{asset("assets/backend/vendors/vmap/maps/jquery.vmap.usa.js")}}'></script>
<script src='{{asset("assets/backend/js/examples/vmap.js")}}'></script>

<!-- Dashboard scripts -->
<script src='{{asset("assets/backend/js/examples/dashboard.js")}}'></script>
<div class="colors">
    <!-- To use theme colors with Javascript -->
    <div class="bg-primary"></div>
    <div class="bg-primary-bright"></div>
    <div class="bg-secondary"></div>
    <div class="bg-secondary-bright"></div>
    <div class="bg-info"></div>
    <div class="bg-info-bright"></div>
    <div class="bg-success"></div>
    <div class="bg-success-bright"></div>
    <div class="bg-danger"></div>
    <div class="bg-danger-bright"></div>
    <div class="bg-warning"></div>
    <div class="bg-warning-bright"></div>
</div>

<!-- App scripts -->
<script src='{{asset("assets/backend/js/app.js")}}'></script>
<script src='{{asset("assets/backend/js/custom.js")}}'></script>

@yield('js')
@yield('navJS')

</body>

</html>

domains/tipposh.com/tipposhFiles/resources/views/backend/layout/errors.blade.php
@if (session('prossesOk'))
    <div class="alert alert-success">
        {{ session('prossesOk') }}
    </div>
@endif
@if (session('prossesError'))
    <div class="alert alert-danger">
        {{ session('prossesError') }}
    </div>
@endif
@if ($errors->any())
    <p class="errorTitle">لطفا خطا های زیر را برطرف نمایید</p>
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif