domains/tipposh.com/tipposhFiles/routes/backend.php
<?php

use Illuminate\Support\Facades\Route;

Route::name('admin.')->group(function () {
    Route::get('login', 'BackendController@login')->name('login');
    Route::post('authentication', 'BackendController@authentication')->name('authentication');

    Route::get('forgetPass', 'AdminController@forgetPassForm')->name('forgetPassForm');
    Route::post('forgetPass', 'AdminController@forgetPass')->name('forgetPass');

    Route::get('changePass/{token}/{email}', 'AdminController@changePassForm')->name('changePassForm');
    Route::post('changePass', 'AdminController@changePass')->name('changePass');


    Route::middleware('adminAuth')->group(function () {
        Route::get('profile', 'BackendController@profile')->name('profile');
        Route::put('profileUpdate', 'BackendController@profileUpdate')->name('profileUpdate');
        Route::post('logout', 'AdminController@logout')->name('logout');
    });
});

Route::name('admin.')->middleware('adminAuth')->group(function () {
    Route::get('/', 'BackendController@dashboard')->name('dashboard');


    //******    admins Rule
    Route::get('rule/{id?}', 'Ad_AdminRuleController@destroy')->name('rule.delete');

    Route::resource('category', 'CategoryController');
    Route::resource('carousel', 'CarouselController');
    Route::resource('service', 'ServiceController');
    Route::resource('setting', 'SettingController');
    Route::resource('menu', 'MenuController');
    Route::resource('brand', 'BrandController');
    Route::resource('admins', 'AdminController');
    Route::resource('users', 'UserController');
    Route::resource('newsletter', 'AdminController');
    Route::resource('userRequestService', 'ServiceUserRequestController');

    Route::resource('order', 'OrderController');
	Route::resource('productDiscount', 'ProductDiscountController');

    Route::get('sale', 'PaymentController@saleAll')->name('sale.index');


    //*************************/ Blog
    Route::prefix('blog')->name('blog.')->group(function () {
        Route::get('addTag', 'BlogController@addTag')->name('addTag');
        Route::post('addTag', 'BlogController@addTag')->name('addTag');
        Route::get('removeTag', 'BlogController@removeTag')->name('removeTag');
        Route::post('removeTag', 'BlogController@removeTag')->name('removeTag');
        Route::post('images', 'BlogController@images')->name('images');
        Route::get('removImage', 'BlogController@removImage')->name('removImage');
    });
    Route::resource('blog', 'BlogController');
    //************/

    //*************************/ Product
    Route::prefix('product')->name('product.')->group(function () {
        Route::get('addTag', 'ProductController@addTag')->name('addTag');
        Route::get('removeTag', 'ProductController@removeTag')->name('removeTag');
        Route::get('removeColor', 'ProductController@removeColor')->name('removeColor');
        Route::get('removImage', 'ProductController@removImage')->name('removImage');
    });
    Route::resource('product', 'ProductController');
    //************/

    //*************************/ productComment
    Route::prefix('comment')->name('comment.')->group(function () {
        Route::get('/', 'ProductCommentController@index')->name('index');
        Route::get('replay', 'ProductCommentController@replay')->name('replay');
        Route::get('userHistory/{id}', 'ProductCommentController@userHistory')->name('userHistory');
        Route::get('changeStatus/{id}', 'ProductCommentController@changeStatus')->name('changeStatus');
        Route::get('destroy/{id}', 'ProductCommentController@delete')->name('delete');
    });
    //************/
});

domains/tipposh.com/tipposhFiles/routes/frontend.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index')->name('index');

Route::get('category/{slug}', 'FrontController@category')->name('category');
Route::post('category/{slug}', 'FrontController@category')->name('category');


Route::get('aboutUs', 'FrontController@aboutUs')->name('aboutUs');
Route::get('contactUs', 'FrontController@contactUs')->name('contactUs');
Route::get('help', 'FrontController@help')->name('help');
Route::get('order', 'FrontController@order')->name('order');

Route::get('userlogin', 'FrontController@userlogin')->name('user.login');
Route::get('userregisterForm', 'FrontController@userregisterForm')->name('user.registerForm');


Route::get('contact', 'FrontController@contact')->name('contact');
Route::get('userContactUs', 'FrontController@userContactUs');

Route::prefix('service')->name('service.')->group(function () {
    Route::get('/', 'ServiceController@services')->name('services');
    Route::get('/{slug}', 'ServiceController@details')->name('details');
});

Route::get('search', 'FrontController@search')->name('search'); // جستجو

Route::get('newsLetter', 'FrontController@newsLetter')->name('newsLetter');

Route::fallback(function () {
    return view('frontend.pages.404');
})->name('404');


Route::get('userServiceRequests', 'ServiceUserRequestController@add');


########### order
Route::prefix('order')->name('order.')->group(function () {
    Route::get('/{id}', 'OrderController@order')->name('new');
    Route::post('Save', 'OrderController@orderSave')->name('orderSave');
});

########### product
Route::prefix('product')->name('product.')->group(function () {
    Route::get('/{slug}', 'ProductController@show')->name('show');
    Route::get('all', 'ProductController@all')->name('all');
    Route::get('comment/Store', 'ProductController@commentStore')->name('commentStore');
});


########### Blog
Route::prefix('blog')->name('blog.')->group(function () {
    Route::get('/', 'BlogController@all')->name('all');
    Route::get('/{slug}', 'BlogController@details')->name('details');
    Route::get('commentStore', 'BlogController@commentStore')->name('commentStore');
    Route::get('category/{id}/{title}', 'BlogController@categoryPosts')->name('categoryPosts');
});


########### user
Route::prefix('user')->name('user.')->middleware('auth:web')->group(function () {
    Route::get('profile', 'UserController@profile')->name('profile');
    Route::post('profile', 'UserController@profileUpdate')->name('profileUpdate');
    Route::get('sale', 'UserController@sale')->name('sale');
    Route::get('basket', 'UserController@basket')->name('basket');
    Route::get('cash', 'UserController@cash')->name('cash');
    Route::get('likes', 'UserController@myLike')->name('likes');
    Route::get('requests', 'UserController@requests')->name('requests');
    Route::get('comments', 'UserController@comments')->name('comments');
    Route::get('removeComments', 'UserController@removeComments');
    Route::get('logout', 'UserController@logout')->name('logout');
    Route::get('password', 'UserController@password')->name('password');
    Route::post('password/update', 'UserController@passwordUpdate')->name('passwordUpdate');
});

Route::prefix('user')->name('user.')->middleware('guest')->group(function () {
    Route::post('loginTakePhone', 'UserController@loginTakePhone')->name('loginTakePhone');
    Route::post('login/VerifyCode', 'UserController@loginVerifyCode')->name('loginVerifyCode');
});


Route::prefix('user')->name('user.')->middleware('guest')->group(function () {
    Route::post('loginWithUsername', 'UserController@loginWithUsername')->name('loginWithUsername')->middleware('throttle:5,1');
});
Route::prefix('user')->name('user.')->group(function () {
    Route::get('like', 'LikeController@likeAndDislike');
});
### End user


########### basket
Route::prefix('basket')->name('basket.')->group(function () {
    Route::get('/', 'BasketController@index')->name('index');
    Route::get('all', 'BasketController@all');
    Route::get('add', 'BasketController@add');
    Route::post('add', 'BasketController@add')->name('addItem');
    Route::get('addOrRemove', 'BasketController@addOrRemove');
    Route::get('update', 'BasketController@update');
    Route::get('remove', 'BasketController@remove');
    Route::get('factor', 'BasketController@factor')->name('factor');
    Route::get('updateBasketAddress', 'BasketController@updateBasketAddress');
    Route::get('factorCompare', 'BasketController@factorCompare');
    Route::get('addDiscountCode', 'BasketController@addDiscountCode');
});
### End Product


Route::get('payment', 'PaymentController@payment')->name('payment');
Route::any('paymentCallback', 'PaymentController@paymentCallback')->name('paymentCallback');



########### Sitemap
Route::get('sitemap.xml','SitemapController@sitemap');
Route::get('sitemap-static.xml','SitemapController@statics');
Route::get('sitemap-category.xml','SitemapController@category');
Route::get('sitemap-post.xml','SitemapController@post');
Route::get('sitemap-product.xml','SitemapController@product');
### End Sitemap

domains/tipposh.com/tipposhFiles/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

domains/tipposh.com/tipposhFiles/app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    protected $table = 'settings';
    public $timestamps = false;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'key',
        'value',
        'type',
    ];
}

domains/tipposh.com/tipposhFiles/app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;
use Image;

use App\Models\Setting;


class SettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $all = Setting::all();
        return view('backend.pages.settings.all', compact('all'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('frontend.pages.settings.single');
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.pages.settings.new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        if (Setting::create(['key' => $request->key])->first()) {
            $setting = Setting::create(['key' => $request->key , 'type' => $request->type]);

            if ($request->type == "photo") {
                if ($request->hasFile('photo')) {
                    $fileType = $request->photo->extension();
                    $rondName = substr(str_shuffle('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'), 1, 10);
                    $imgFullName = "assets/images/$rondName.$fileType";
                    $image = Image::make($request->file('photo'));
                    $image->save($imgFullName, 100);

                    $setting->update(['value' => $imgFullName]);
                }
            } elseif ($request->type == "des")
                $setting->update(['value' => $request->description]);
            else
                $setting->update(['value' => $request->summary]);
        }

        return redirect()->back()->with('prossesOk', 'عملیات  با موفقیت انجام شد');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $setting = Setting::find($id);
        return view('backend.pages.settings.edit', compact('setting'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Setting::find($id)->update(['key' => $request->key , 'type' => $request->type]);
        if ($request->type == "photo") {
            if ($request->hasFile('photo')) {
                $fileType = $request->photo->extension();
                $rondName = substr(str_shuffle('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'), 1, 10);
                $imgFullName = "assets/images/$rondName.$fileType";
                $image = Image::make($request->file('photo'));
                $image->save($imgFullName, 100);

                Setting::find($id)->update(['value' => $imgFullName]);
            }
        } elseif ($request->type == "des")
            Setting::find($id)->update(['value' => $request->description]);
        else
            Setting::find($id)->update(['value' => $request->summary]);


        return redirect()->back()->with('prossesOk', 'عملیات  با موفقیت انجام شد');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Setting::find($id);
        if (file_exists($item->value))
            unlink($item->value);

        $delete = $item->delete();
        return redirect()->back()->with('prossesOk', 'عملیات  با موفقیت انجام شد ');

    }

}

domains/tipposh.com/tipposhFiles/resources/views/backend/pages/settings/all.blade.php
@extends('backend.layout.app')

@section('title') تنظیمات  @stop

@section('pageInfo')
    <h3 class="page-title">تنظیمات </h3>
    <!-- begin::breadcrumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a>برنامه ها</a></li>
            <li class="breadcrumb-item"><a href="{{route('admin.setting.index')}}"> تنظیمات </a></li>
            <li class="breadcrumb-item active" aria-current="page">همه</li>
        </ol>
    </nav>
    <!-- end::breadcrumb -->
@stop

@section('css')
    <style>
        .table:not(.table-bordered) td {
            white-space: unset;
        }
    </style>
@endsection

@section('js') @endsection

@section('content')
    <main class="main-content">
        <div class="row">

            <div class="col-md-12">
                @include('backend.layout.errors')
            </div>


            <div class="col-md-12">

                <div class="card">
                    <div class="card-body">
                        <h6 class="card-title">لیست تنظیمات </h6>

                        <a href="{{route('admin.setting.create')}}" title="اضافه کردن رکود جدید" class="float-right">
                            <button type="button" class="btn btn-whatsapp btn-floating btn-lg btn-pulse">
                                <i class="ti-plus"></i>
                            </button>
                        </a>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">کلید</th>
                                    <th scope="col" width="70%">مقدار</th>
                                    <th class="text-right" scope="col">عمل</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($all as $key => $item)
                                    <tr>
                                        <th scope="row">{{$key + 1}}</th>

                                        <td>{{\App\Models\SettingItems::where('en_name',$item->key)->first()->fa_name}}</td>

                                        <td>
                                            @if($item->type == "photo")
                                                @if(file_exists($item->value))
                                                    <img src="{{asset($item->value)}}" alt="">
                                                @endif
                                            @elseif($item->type == "sum")
                                                {{$item->value}}
                                            @else
                                               متن صفحه ای ، برای دیدن کلید مشاهده را بزنید
                                            @endif
                                        </td>

                                        <td class="text-right">
                                            <div class="dropdown">
                                                <a href="#" class="btn btn-light btn-floating btn-icon btn-sm"
                                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a href="{{route('admin.setting.edit', $item->id)}}">
                                                        <button class="dropdown-item" type="button">
                                                            مشاهده و بروزرسانی
                                                        </button>
                                                    </a>

                                                    <button class="dropdown-item" type="button"
                                                            onclick="deleteRecordFromTable({{$item->id}})">حذف کردن
                                                    </button>

                                                    <form id="deleteRecordFrom_{{$item->id}}"
                                                          action="{{route('admin.setting.destroy', $item->id)}}"
                                                          method="post" style="display: none;">
                                                        @csrf
                                                        @method('delete')
                                                    </form>

                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection

domains/tipposh.com/tipposhFiles/resources/views/backend/pages/settings/edit.blade.php
@extends('backend.layout.app')

@section('title')  نمایش  @stop

@section('pageInfo')
    <h3 class="page-title"> تنظیمات </h3>
    <!-- begin::breadcrumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a>برنامه ها</a></li>
            <li class="breadcrumb-item"><a href="{{route('admin.setting.index')}}"> تنظیمات </a></li>
            <li class="breadcrumb-item active" aria-current="page">نمایش</li>
        </ol>
    </nav>
    <!-- end::breadcrumb -->
@stop

@section('css')
    <style>
        .el-display-none {
            display: none;
        }

        .el-display-block {
            display: block;
        }
    </style>
@stop


@section('content')

    <main class="main-content">
        <div class="row">

            <div class="col-md-12">
                @include('backend.layout.errors')
            </div>


            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">

                        <h6 class="card-title">نمایش پست </h6>


                        <form method="post" id="addForm" action="{{route('admin.setting.update' , $setting->id)}}"
                              enctype="multipart/form-data">
                            @csrf
                            @method('put')

                            <div class="form-row">

                                <div class="col-md-5 mt-3 mb-3">
                                    <label for="type"> قصد ذخیره سازی چه چیزی دارید </label>
                                    <select id="type" name="type" class="form-control" placeholder=" کلید ">
                                        <option value="sum" @if($setting->type == "sum") selected @endif > متن کوتاه</option>
                                        <option value="photo" @if($setting->type == "photo") selected @endif > تصویر</option>
                                        <option value="des" @if($setting->type == "des") selected @endif>متن بلند(بیش از 10 خط ، متن صفحه ای)</option>
                                    </select>
                                </div>


                                <div class="col-md-7 mt-3 mb-3">
                                    <label for="key"> کلید </label>
                                    <select id="key" name="key" class="form-control select2" placeholder=" کلید ">
                                        
                                        @foreach(\App\Models\SettingItems::all() as $item)
                                            <option value="{{$item->en_name}}"
                                                    @if($setting->key==$item->en_name)selected @endif>{{$item->fa_name}}</option>
                                        @endforeach

                                    </select>
                                </div>

                            </div>


                            <div class="form-row @if($setting->type == "sum") el-display-block @else el-display-none @endif ">
                                <div class="col-md-12 mt-3 mb-3">
                                    <label for="summary"> متن </label>
                                    <input type="text" id="sum" name="summary" class="form-control"
                                           placeholder=" متن " value="{{$setting->value}}">
                                </div>
                            </div>

                            <div class="form-row @if($setting->type == "photo") el-display-block @else el-display-none @endif ">
                                <div class="col-md-12 mt-3 mb-3">
                                    <label for="photo"> انتخاب عکس </label>
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="photo" name="photo">
                                        <label class="custom-file-label" for="photo">انتخاب عکس</label>
                                    </div>
                                </div>
                            </div>


                            <div class="form-row @if($setting->type == "des") el-display-block @else el-display-none @endif">
                                <div class="col-md-12 m-1 mb-3">
                                    <div class="form-group">
                                        <label for="description">متن</label>
                                        <textarea class="form-control" id="des" name="description"
                                                  placeholder="متن">{{$setting->value}}</textarea>
                                    </div>
                                </div>
                            </div>



                            <button class="btn btn-primary submit" type="submit">ثبت</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection

@section('js')
    <script src="{{asset('assets/backend/vendors/ckeditor/ckeditor.js')}}"></script>
    <link rel="stylesheet" href="{{ asset('assets/backend/vendors/select2/css/select2.min.css') }}">
    <script type="text/javascript" src="{{ asset('assets/backend/vendors/select2/js/select2.min.js') }}"></script>

    <script>
        $('.select2').select2();

        $(function () {
            CKEDITOR.replace("des");
        });

        $('#type').on('change', function () {
            var element = $(this).val();
            $('.el-display-block').removeClass('el-display-block').addClass('el-display-none');
            $("#"+element).parents('.form-row').removeClass('el-display-none').addClass('el-display-block');
        })

    </script>
@stop

domains/tipposh.com/tipposhFiles/resources/views/backend/pages/settings/new.blade.php
@extends('backend.layout.app')

@section('title')  جدید  @stop

@section('pageInfo')
    <h3 class="page-title">تنظیمات </h3>
    <!-- begin::breadcrumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a>برنامه ها</a></li>
            <li class="breadcrumb-item"><a href="{{route('admin.setting.index')}}"> تنظیمات </a></li>
            <li class="breadcrumb-item active" aria-current="page">جدید</li>
        </ol>
    </nav>
    <!-- end::breadcrumb -->
@stop

@section('css')
    <style>
        .el-display-none {
            display: none;
        }

        .el-display-block {
            display: block;
        }
    </style>
@stop

@section('content')

    <main class="main-content">
        <div class="row">

            <div class="col-md-12">
                @include('backend.layout.errors')
            </div>


            <div class="col-md-12">

                <div class="card">
                    <div class="card-body">

                        <h6 class="card-title">اضافه کردن </h6>

                        <form method="post" action="{{route('admin.setting.store')}}" enctype="multipart/form-data">
                            @csrf

                            <div class="form-row">

                                <div class="col-md-5 mt-3 mb-3">
                                    <label for="status"> شما قصد ذخیره سازی چه چیزی دارید </label>
                                    <select id="status" name="type" class="form-control" placeholder=" وضعیت ">
                                        <option value="sum"> متن کوتاه</option>
                                        <option value="photo"> تصویر</option>
                                        <option value="des">متن بلند(بیش از 10 خط ، متن صفحه ای)</option>
                                    </select>
                                </div>


                                <div class="col-md-7 mt-3 mb-3">
                                    <label for="key"> کلید </label>
                                    <select id="key" name="key" class="form-control select2" placeholder=" کلید ">

                                        @foreach(\App\Models\SettingItems::all() as $item)
                                            <option value="{{$item->en_name}}">{{$item->fa_name}}</option>
                                        @endforeach

                                    </select>
                                </div>

                            </div>


                            <div class="form-row el-display-block">
                                <div class="col-md-12 mt-3 mb-3">
                                    <label for="summary"> متن </label>
                                    <input type="text" id="summary" name="summary" class="form-control"
                                           placeholder=" متن " value="{{old('summary')}}">
                                </div>
                            </div>

                            <div class="form-row el-display-none">
                                <div class="col-md-12 mt-3 mb-3">
                                    <label for="photo"> انتخاب عکس </label>
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="photo" name="photo">
                                        <label class="custom-file-label" for="photo">انتخاب عکس</label>
                                    </div>
                                </div>
                            </div>


                            <div class="form-row el-display-none">
                                <div class="col-md-12 m-1 mb-3">
                                    <div class="form-group">
                                        <label for="description">متن</label>
                                        <textarea class="form-control" id="des" name="description"
                                                  placeholder="متن">{{old('description')}}</textarea>
                                    </div>
                                </div>
                            </div>


                            <button class="btn btn-primary submit" type="submit">ثبت</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection

@section('js')
    <script src="{{asset('assets/backend/vendors/ckeditor/ckeditor.js')}}"></script>
    <link rel="stylesheet" href="{{ asset('assets/backend/vendors/select2/css/select2.min.css') }}">
    <script type="text/javascript" src="{{ asset('assets/backend/vendors/select2/js/select2.min.js') }}"></script>
    
    <script>
        $('.select2').select2();

        $(function () {
            CKEDITOR.replace("des");
        });

        $('#status').on('change', function () {
            var element = $(this).val();
            $('.el-display-block').removeClass('el-display-block').addClass('el-display-none');
            $("#" + element).parents('.form-row').removeClass('el-display-none').addClass('el-display-block');
        })

    </script>
@stop