domains/tipposh.com/tipposhFiles/routes/backend.php
<?php

use Illuminate\Support\Facades\Route;

Route::name('admin.')->group(function () {
    Route::get('login', 'BackendController@login')->name('login');
    Route::post('authentication', 'BackendController@authentication')->name('authentication');

    Route::get('forgetPass', 'AdminController@forgetPassForm')->name('forgetPassForm');
    Route::post('forgetPass', 'AdminController@forgetPass')->name('forgetPass');

    Route::get('changePass/{token}/{email}', 'AdminController@changePassForm')->name('changePassForm');
    Route::post('changePass', 'AdminController@changePass')->name('changePass');


    Route::middleware('adminAuth')->group(function () {
        Route::get('profile', 'BackendController@profile')->name('profile');
        Route::put('profileUpdate', 'BackendController@profileUpdate')->name('profileUpdate');
        Route::post('logout', 'AdminController@logout')->name('logout');
    });
});

Route::name('admin.')->middleware('adminAuth')->group(function () {
    Route::get('/', 'BackendController@dashboard')->name('dashboard');


    //******    admins Rule
    Route::get('rule/{id?}', 'Ad_AdminRuleController@destroy')->name('rule.delete');

    Route::resource('category', 'CategoryController');
    Route::resource('carousel', 'CarouselController');
    Route::resource('service', 'ServiceController');
    Route::resource('setting', 'SettingController');
    Route::resource('menu', 'MenuController');
    Route::resource('brand', 'BrandController');
    Route::resource('admins', 'AdminController');
    Route::resource('users', 'UserController');
    Route::resource('newsletter', 'AdminController');
    Route::resource('userRequestService', 'ServiceUserRequestController');

    Route::resource('order', 'OrderController');
	Route::resource('productDiscount', 'ProductDiscountController');

    Route::get('sale', 'PaymentController@saleAll')->name('sale.index');


    //*************************/ Blog
    Route::prefix('blog')->name('blog.')->group(function () {
        Route::get('addTag', 'BlogController@addTag')->name('addTag');
        Route::post('addTag', 'BlogController@addTag')->name('addTag');
        Route::get('removeTag', 'BlogController@removeTag')->name('removeTag');
        Route::post('removeTag', 'BlogController@removeTag')->name('removeTag');
        Route::post('images', 'BlogController@images')->name('images');
        Route::get('removImage', 'BlogController@removImage')->name('removImage');
    });
    Route::resource('blog', 'BlogController');
    //************/

    //*************************/ Product
    Route::prefix('product')->name('product.')->group(function () {
        Route::get('addTag', 'ProductController@addTag')->name('addTag');
        Route::get('removeTag', 'ProductController@removeTag')->name('removeTag');
        Route::get('removeColor', 'ProductController@removeColor')->name('removeColor');
        Route::get('removImage', 'ProductController@removImage')->name('removImage');
    });
    Route::resource('product', 'ProductController');
    //************/

    //*************************/ productComment
    Route::prefix('comment')->name('comment.')->group(function () {
        Route::get('/', 'ProductCommentController@index')->name('index');
        Route::get('replay', 'ProductCommentController@replay')->name('replay');
        Route::get('userHistory/{id}', 'ProductCommentController@userHistory')->name('userHistory');
        Route::get('changeStatus/{id}', 'ProductCommentController@changeStatus')->name('changeStatus');
        Route::get('destroy/{id}', 'ProductCommentController@delete')->name('delete');
    });
    //************/
});

domains/tipposh.com/tipposhFiles/routes/frontend.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index')->name('index');

Route::get('category/{slug}', 'FrontController@category')->name('category');
Route::post('category/{slug}', 'FrontController@category')->name('category');


Route::get('aboutUs', 'FrontController@aboutUs')->name('aboutUs');
Route::get('contactUs', 'FrontController@contactUs')->name('contactUs');
Route::get('help', 'FrontController@help')->name('help');
Route::get('order', 'FrontController@order')->name('order');

Route::get('userlogin', 'FrontController@userlogin')->name('user.login');
Route::get('userregisterForm', 'FrontController@userregisterForm')->name('user.registerForm');


Route::get('contact', 'FrontController@contact')->name('contact');
Route::get('userContactUs', 'FrontController@userContactUs');

Route::prefix('service')->name('service.')->group(function () {
    Route::get('/', 'ServiceController@services')->name('services');
    Route::get('/{slug}', 'ServiceController@details')->name('details');
});

Route::get('search', 'FrontController@search')->name('search'); // جستجو

Route::get('newsLetter', 'FrontController@newsLetter')->name('newsLetter');

Route::fallback(function () {
    return view('frontend.pages.404');
})->name('404');


Route::get('userServiceRequests', 'ServiceUserRequestController@add');


########### order
Route::prefix('order')->name('order.')->group(function () {
    Route::get('/{id}', 'OrderController@order')->name('new');
    Route::post('Save', 'OrderController@orderSave')->name('orderSave');
});

########### product
Route::prefix('product')->name('product.')->group(function () {
    Route::get('/{slug}', 'ProductController@show')->name('show');
    Route::get('all', 'ProductController@all')->name('all');
    Route::get('comment/Store', 'ProductController@commentStore')->name('commentStore');
});


########### Blog
Route::prefix('blog')->name('blog.')->group(function () {
    Route::get('/', 'BlogController@all')->name('all');
    Route::get('/{slug}', 'BlogController@details')->name('details');
    Route::get('commentStore', 'BlogController@commentStore')->name('commentStore');
    Route::get('category/{id}/{title}', 'BlogController@categoryPosts')->name('categoryPosts');
});


########### user
Route::prefix('user')->name('user.')->middleware('auth:web')->group(function () {
    Route::get('profile', 'UserController@profile')->name('profile');
    Route::post('profile', 'UserController@profileUpdate')->name('profileUpdate');
    Route::get('sale', 'UserController@sale')->name('sale');
    Route::get('basket', 'UserController@basket')->name('basket');
    Route::get('cash', 'UserController@cash')->name('cash');
    Route::get('likes', 'UserController@myLike')->name('likes');
    Route::get('requests', 'UserController@requests')->name('requests');
    Route::get('comments', 'UserController@comments')->name('comments');
    Route::get('removeComments', 'UserController@removeComments');
    Route::get('logout', 'UserController@logout')->name('logout');
    Route::get('password', 'UserController@password')->name('password');
    Route::post('password/update', 'UserController@passwordUpdate')->name('passwordUpdate');
});

Route::prefix('user')->name('user.')->middleware('guest')->group(function () {
    Route::post('loginTakePhone', 'UserController@loginTakePhone')->name('loginTakePhone');
    Route::post('login/VerifyCode', 'UserController@loginVerifyCode')->name('loginVerifyCode');
});


Route::prefix('user')->name('user.')->middleware('guest')->group(function () {
    Route::post('loginWithUsername', 'UserController@loginWithUsername')->name('loginWithUsername')->middleware('throttle:5,1');
});
Route::prefix('user')->name('user.')->group(function () {
    Route::get('like', 'LikeController@likeAndDislike');
});
### End user


########### basket
Route::prefix('basket')->name('basket.')->group(function () {
    Route::get('/', 'BasketController@index')->name('index');
    Route::get('all', 'BasketController@all');
    Route::get('add', 'BasketController@add');
    Route::post('add', 'BasketController@add')->name('addItem');
    Route::get('addOrRemove', 'BasketController@addOrRemove');
    Route::get('update', 'BasketController@update');
    Route::get('remove', 'BasketController@remove');
    Route::get('factor', 'BasketController@factor')->name('factor');
    Route::get('updateBasketAddress', 'BasketController@updateBasketAddress');
    Route::get('factorCompare', 'BasketController@factorCompare');
    Route::get('addDiscountCode', 'BasketController@addDiscountCode');
});
### End Product


Route::get('payment', 'PaymentController@payment')->name('payment');
Route::any('paymentCallback', 'PaymentController@paymentCallback')->name('paymentCallback');



########### Sitemap
Route::get('sitemap.xml','SitemapController@sitemap');
Route::get('sitemap-static.xml','SitemapController@statics');
Route::get('sitemap-category.xml','SitemapController@category');
Route::get('sitemap-post.xml','SitemapController@post');
Route::get('sitemap-product.xml','SitemapController@product');
### End Sitemap

domains/tipposh.com/tipposhFiles/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

domains/tipposh.com/tipposhFiles/app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Admin;

class Blog extends Model
{
    protected $table = 'blog';
    protected $fillable = [
        'title',
        'slug',
        'admin_id',
        'description',
        'summary' ,
        'status',
        'category_id',
        'image_alt',
        'iamge_title',
        'key_word',
        'index_photo',
        'main_photo'
    ];


    /**
     ****    related Products
     */
    public function relatedPost()
    {
        return Blog::where('category_id', $this->skill_id)
            ->where('id', '!=', $this->id)->where('status', 1)
            ->orderBy('id', 'desc')->take(10)
            ->get();
    }


    //    نظرات پست
    public function blogComment()
    {
        return $this->hasMany(BlogComment::class)->where('status',1)->where('parent_id' , 0);
    }

    //    عکسهای پست
    public function blogImages()
    {
        return $this->hasMany(BlogImages::class);
    }

    //   پست های اخیر     
    public function newBlogs()
    {
        return $this->where('status', 1)->orderBy('id', 'asc')->take(10)->get();
    }

    //  برچسب های پست
    public function blogTag()
    {
        return $this->hasMany(BlogTag::class);
    }

    //    ناشر
    public function auther()
    {
        return $this->belongsTo(Admin::class, 'admin_id', 'id');
    }

    //    دسته بندی
    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }
}

domains/tipposh.com/tipposhFiles/resources/views/backend/pages/blog/all.blade.php
@extends('backend.layout.app')

@section('title') همه پست ها  @stop

@section('pageInfo')
    <h3 class="page-title">وبلاگ </h3>
    <!-- begin::breadcrumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a>برنامه ها</a></li>
            <li class="breadcrumb-item"><a> وبلاگ </a></li>
            <li class="breadcrumb-item active" aria-current="page">همه</li>
        </ol>
    </nav>
    <!-- end::breadcrumb -->
@stop

@section('js')
    <script src="{{ asset('assets/backend/demo/blog.js') }}"></script>
@endsection

@section('content')
    <main class="main-content">
        <div class="row">
            <div class="col-md-12">

                <div class="col-md-12">
                    @include('backend.layout.errors')
                </div>

                <div class="card">
                    <div class="card-body">
                        <h6 class="card-title">لیست پست ها </h6>

                        <a href="{{route('admin.blog.create')}}" title="اضافه کردن رکود جدید" class="float-right">
                            <button type="button" class="btn btn-whatsapp btn-floating btn-lg btn-pulse">
                                <i class="ti-plus"></i>
                            </button>
                        </a>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">عنوان</th>
                                    <th scope="col">وضعیت نمایش</th>
                                    <th scope="col">ناشر</th>
                                    <th scope="col">عکس</th>
                                    <th class="text-right" scope="col">عمل</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($all as $key => $item)
                                    <tr>
                                        <th scope="row">{{$key + 1}}</th>
                                        <td>{{$item->title}}</td>
                                        <td>
                                            @if($item->status == 1)
                                                نمایش بده
                                            @else
                                                نمایش نده
                                            @endif
                                        </td>

                                        <td>{{ $item->auther()->first()->name }}</td>
                                        <td><img src="{{asset($item->index_photo)}}" alt=""></td>


                                        <td class="text-right">
                                            <div class="dropdown">
                                                <a href="#" class="btn btn-light btn-floating btn-icon btn-sm"
                                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a href="{{route('admin.blog.edit', $item->id)}}">
                                                        <button class="dropdown-item" type="button">
                                                            مشاهده و بروزرسانی
                                                        </button>
                                                    </a>

                                                    <button class="dropdown-item" type="button"
                                                            onclick="deleteRecordFromTable({{$item->id}})">حذف کردن
                                                    </button>

                                                    <form id="deleteRecordFrom_{{$item->id}}"
                                                          action="{{route('admin.blog.destroy', $item->id)}}"
                                                          method="post" style="display: none;">
                                                        @csrf
                                                        @method('delete')
                                                    </form>

                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection

domains/tipposh.com/tipposhFiles/resources/views/backend/pages/blog/edit.blade.php
@extends('backend.layout.app')

@section('title')  نمایش پست   @stop

@section('pageInfo')
    <h3 class="page-title">وبلاگ </h3>
    <!-- begin::breadcrumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a>برنامه ها</a></li>
            <li class="breadcrumb-item"><a> وبلاگ </a></li>
            <li class="breadcrumb-item active" aria-current="page">نمایش</li>
        </ol>
    </nav>
    <!-- end::breadcrumb -->
@stop

@section('css')

    <style>
        .newTagAdd {
            margin-left: 15px;
            float: right;
        }

        .newTagAdd span,
        .blogMoreImagesUrls span {
            color: #f70000;
            position: relative;
            top: -6px;
            margin-right: -8px;
            cursor: pointer;
            z-index: 100;
            float: left;
        }

        .blogMoreImagesUrls tr td {
            text-align: left
        }

        input[list] {
            width: 100%;
            height: 40px;
            padding: 15px;
            border: none;
            border-radius: 5px;
        }
    </style>

@stop

@section('content')

    <main class="main-content" data-ng-app="myApp" data-ng-controller="blogJsController">
        <div class="row">
            <div class="col-md-12">

                <div class="col-md-12">
                    @include('backend.layout.errors')
                </div>

                <div class="card">
                    <div class="card-body">

                        <h6 class="card-title">نمایش پست </h6>

                        <div class="form-row">
                            <div class="col-md-4" style="padding-right:0 ; padding-left:20px">
                                <label for="title">اضافه کردن عکس های داخل صفحه </label>
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="customFile" name="photo"
                                           onchange="angular.element(this).scope().uploadFile(this.files)">
                                    <label class="custom-file-label" for="customFile">انتخاب فایل</label>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>مسیر عکس ها</th>
                                    </tr>
                                    </thead>
                                    <tbody class="blogMoreImagesUrls">
                                    @foreach ($blog->blogImages as $item)
                                        <tr>
                                            <td> http://127.0.0.1:8000/assets/images/blog/{{ $item->id }}.jpg <span
                                                        data-id="{{ $item->id }}">x</span></td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>


                        <form method="post" id="addForm" action="{{route('admin.blog.update' , $blog->id)}}"
                              enctype="multipart/form-data">
                            @csrf
                            @method('put')

                            <div class="form-row">
                                <div class="col-md-12 mt-3 mb-3">
                                    <label for="title"> عنوان </label>
                                    <input type="text" id="title" name="title" class="form-control"
                                           placeholder=" عنوان " value="{{$blog->title}}">
                                </div>

                            </div>

                            <div class="form-row">
                                <div class="col-md-12 mb-3">
                                    <label for="summary"> خلاصه </label>
                                    <textarea name="summary" id="summary" rows="5" class="form-control"
                                              placeholder="خلاصه مطلب">{{$blog->summary}}</textarea>
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="col-md-4 mb-3">
                                    <label for="menu_id"> دسته بندی </label>
                                    <select name="category" id="category" class="form-control">
                                        <option value="0"> ---</option>
                                        @foreach ($allCategory as $item)
                                            <option value="{{ $item->id }}" @isset($blog->category()->first()->id)
                                            @if($item->id == $blog->category()->first()->id)
                                            selected
                                                    @endif
                                                    @endisset
                                            > {{ $item->name }} </option>

                                            @foreach ($item->Childs as $child)
                                                <option value="{{ $child->id }}" @isset($blog->category()->first()->id)
                                                @if($child->id == $blog->category()->first()->id)
                                                selected
                                                        @endif
                                                        @endisset
                                                >---> {{ $child->name }} </option>
                                            @endforeach

                                        @endforeach
                                    </select>
                                </div>

                                <div class="col-md-4 mb-3">
                                    <label for="key_word"> کلمه کلیدی اصلی </label>
                                    <input type="text" id="key_word" name="key_word" class="form-control"
                                           placeholder=" کلمه کلیدی اصلی " value="{{$blog->key_word}}">
                                </div>

                                <div class="col-md-4 mb-3">
                                    <label for="validationServer04">وضعیت</label>
                                    <div class="form-group">
                                        <div class="custom-control custom-switch custom-checkbox-success">
                                            <input type="checkbox" class="custom-control-input" id="customSwitch2_"
                                                   @if($blog->status == 1) checked @endif name="status">
                                            <label class="custom-control-label" for="customSwitch2_">نمایش یا عدم
                                                نمایش</label>
                                        </div>
                                    </div>
                                </div>

                            </div>

                            <div class="form-row">
                                <div class="col-md-3 mb-3">
                                    <label for="main_photo"> انتخاب عکس اصلی </label>
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="main_photo" name="main_photo">
                                        <label class="custom-file-label" for="main_photo">انتخاب فایل</label>
                                    </div>
                                </div>

                                <div class="col-md-3 mb-3">
                                    <label for="index_photo"> انتخاب عکس نمایه </label>
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="index_photo"
                                               name="index_photo">
                                        <label class="custom-file-label" for="index_photo">انتخاب فایل</label>
                                    </div>

                                </div>

                                <div class="col-md-3 mb-3">
                                    <label for="image_alt">alt عکس </label>
                                    <input type="text" id="image_alt" name="image_alt" class="form-control"
                                           placeholder="  آلت عکس شاخص " value="{{$blog->image_alt}}">
                                </div>

                                <div class="col-md-3 mb-3">
                                    <label for="iamge_title">title عکس </label>
                                    <input type="text" id="iamge_title" name="iamge_title" class="form-control"
                                           placeholder="  عنوان عکس شاخص " value="{{$blog->iamge_title}}">
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="col-md-12 mt-3 mb-3">
                                    <label for="blogTag"><span class="pull-left"> تگ ها : </span><span id="allBlogTags">
                                           @foreach ($allBlogTags as $item)
                                                <b class="newTagAdd">{{ $item->caption }}<span data-id={{ $item->id }}>x<span></b>
                                            @endforeach
                              </span></label><br>
                                    <input type="text" id="blogTag" class="form-control" style="width:31.2% ;">
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="col-md-12 m-1 mb-3">
                                    <div class="form-group">
                                        <label for="exampleFormControlTextarea1">توضیحات</label>
                                        <textarea class="form-control" id="exampleFormControlTextarea1"
                                                  name="description"
                                                  rows="3">{{$blog->description}}</textarea>
                                    </div>
                                </div>
                            </div>


                            <input type="hidden" id="blog_id" name="blog_id">
                            {{-- مورد نیاز آنگولار --}}
                            <input type="hidden" id="blog_images_id" name="blog_images_id">


                            <button class="btn btn-primary submit" type="button">ثبت</button>

                            <input type="hidden" id="curentSidebarMenu" data-page="edit">
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection

@section('js')
    <script src="{{asset('assets/backend/vendors/ckeditor/ckeditor.js')}}"></script>
    {{--<script src="{{asset('assets/backend/js/examples/ckeditor.js')}}"></script>--}}

    <!-- Angular -->
    <script src="{{ asset('assets/backend/vendors/Angular/angular.min.js')}}"></script>
    <script src="{{ asset('assets/backend/vendors/Angular/controller/angularJsApp.js') }}"></script>
    <script src="{{ asset('assets/backend/vendors/Angular/controller/blogJsController.js') }}"></script>

    <script src="{{ asset('assets/backend/vendors/demo/blog.js') }}"></script>

    <script>
        $('input[list]').on('change', function () {
            var options = $('option', this.list).map(function () {
                return this.value
            }).get();
            if (options.indexOf(this.value) === -1) {
                this.value = "";
            }
        });
    </script>

@stop